name: cal-nc
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - configparser>=3.5
  - h5py>=2.8
  - hdf4>=4.2
  - hdf5>=1.10
  - ipython
  - markupsafe
  - matplotlib>=2.2
  - netcdf4>=1.4
  - numpy>=1.15
  - numpy-base>=1.15
  - pandas>=0.23
  - pathlib2
  - pint>=0.9
  - pip
  - python>=3.3
  - python-dateutil=2.7
  - scipy>=1.1
  - seaborn>=0.9
  - sphinx>=1.8
  - sphinx_rtd_theme
  - sphinxcontrib>=1.0
  - sphinxcontrib-websupport>=1.1
  - xarray>=0.11
  - yaml
