

import datetime, pytz
import numpy as np

import pdb

class Generic():
    """
    Minimal parent class for instrument-specific parsing and processing
    of calibration data suitable for writing to the calibration netCDF.
    """

    def __init__(self,ds):
        """

        :param ds: dataset from ingested cal_nc file
            Note that cal_nc file as been read using r+. Thus variables (?)
            and attributes cannot be appended to. Values must be read to
            a python variable, the nc key deleted, then rewritten with
            appropriate modfications.
        :type ds:  netCDF4.dataset
        :returns ds:
        """
        self.dataset = ds


    def __str__(self):
        """
        Help, specifically with regards to structure of update() method if
        it exists. If update() does not exist then use docstr of processor
        class __init__()
        """

        # To print name of instance use: type(self).__name__
        import pdb

        h1 = self.__doc__

        try:
            h2 = h1 + '\n' + self.update.__doc__
        except AttributeError:
            pdb.set_trace()
            h2 = h1

        try:
            h3 = h2  + '\n' + self._add__str__()
        except AttributeError:
            pdb.set_trace()
            h3 = h2

        return h3


    def update_hist(self,update=None):
        """
        Update the global history attribute.

        The history nc attribute is a single string of comma-delineated text.

        :param update: Update for history string. If None (default) then
            auto-generate string based on today's date. If given then append
            update/s to history attribute string. Any ``<now>`` or ``<today>``
            strings are changed to today's date.
        :type update: List
        """

        t_ = datetime.datetime.now(pytz.utc).replace(microsecond=0).strftime('%Y%m%d')

        if update is None:
            # With datetime v3.6 can use timespec='seconds' to drop ms
            # Timezone aware timestamp is generated by default.
            update = '{} Auto update'.format(t_)

        elif update is 'NA':
            # This assumes that all updates have been handled in the cdl
            # file. So nothing needs to be done here.
            update = ''

        elif hasattr(update,'__iter__'):
            # If is a list of strings then join
            update = ', '.join(update[:])

        # Change any shortcuts to today's date
        update = update.replace('<today>',t_).replace('<now>',t_)

        hist_ = self.dataset.history
        del(self.dataset.history)
        self.dataset.history = '{}, {}'.format(hist_,update)


    def update_user(self,update=None):
        """
        Update the global username attribute.

        The username nc attribute is a single string of comma-delineated text.

        :param update: Update for username string. If None (default) then
            ask user, usually given as 'username <user@email>'. If given
            then append username/s to existing attribute string.
        :type update: List
        """

        if update is None:
            # May be able to automatically generate a username but
            # ask user to be sure.
            update = input('\nEnter username <email> [Enter for cdl]: ')

        elif update is 'NA':
            # This assumes that all updates have been handed in the cdl
            # file. So nothing needs to be done here
            update = ''

        elif hasattr(update,'__iter__'):
            # If is a list of strings then join
            update = ', '.join(update[:])

        else:
            user_ = self.dataset.username
            del(self.dataset.username)
            self.dataset.username = '{}, {}'.format(user_,update)


    def change_val(self,var,old_val,new_val):
        """
        Method to change a single variable/attribute value.

        The variable or attribute name must be given along with the old
        value, ``old_val``, that is to be change to ``new_val``. If ``old_val``
        is not found then nothing is done.

        """

        pass